### ISSUE TITLE
Deploying front-end

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#119]
On SE1, you can deploy your front-end to ipfs, s3 and surge:

![image](https://user-images.githubusercontent.com/2486142/215706711-51ebf0fd-0f4e-4113-b8b4-2a9c77a6b27a.png)

I think it's super handy to have this functionality built-in, but, following the SE2 motto (keep it simple & minimal 🫡) I think we don't want to have all the options, at least for now.

From what I've seen, most of the people use surge (`yarn build` + `yarn surge`), since it's 0-config and it gives you an URL directly. I guess IPFS will also make sense at some point.

Also since we are using NextJS, we can only deploy to Surge (or any other "static sites" hosting) when using client side rendering (no ssr, api routes, etc). We can mention Vercel in the DOCS for people who needs server functionalities. 

Thoughts? @technophile-04 @rin-st

**Comment by rin-st** [comment]
I agree, surge is the simplest way and enough for now. We can consider Vercel or alternatives in the future if ssg/ssr will be needed.

What do you think about the possibility of deploying only the UI page with our header and footer(with SE icon/'Built with SE' message)? As a user, I don't need home/debug pages after deploying.

**Comment by carletex** [comment]
> What do you think about the possibility of deploying only the UI page with our header and footer(with SE icon/'Built with SE' message)? As a user, I don't need home/debug pages after deploying.

Right now people would need to remove those pages (which is not a big deal) + deploy. I think making the "magic" (removing pages, or other stuff) on deploy could be tricky.

Also, we could consider removing the Homepage for good....and showing some text + the debug contract stuff.

But maybe, in the future, we could build some script to clean SE-2. e.g.:
- a script to remove all the demo pages & debug
- a script to remove all the TW classes (for people that want to use their own classes, or UI system)
- ...

Too many options!

But let's keep focusing on the core stuff and iterate. We'll have a bunch of feedback when people start using it.

**Comment by technophile-04** [comment]
Love the discussion and suggestions here. 

1. I think this is the right time for drafting a PR for `yarn surge` (`surge` seems simple, minimal nd comfortable for se-1 devs too ) what do you guys think? Because having a build in functionality to deploy is really great / handy / core before we start sharing with others
2. having a way to deploy to `ipfs` is really great to have and have alot of discussion on Twitter recently that you should deploy your app to a decentralized service too. I saw `fleek` has some cli, checkout -> [@fleekhq/fleek-cli](https://www.npmjs.com/package/@fleekhq/fleek-cli) maybe we can explore this or even the current se-1 approach is fine. Also its not important at the moment but really good to have before we start sharing. 


> Also, we could consider removing the Homepage for good....and showing some text + the debug contract stuff on init

Why? I like the homepage 😅, I see developers/myself taking inspiration from `example-ui.tsx` file and directly start editing `index.tsx`(Homepage). if we have `debug contract` on Homepage/`index.tsx` itself then I cannot tinker with contract simultaneously while building UI, I like to edit UI on `localhost:3000` and tinker  on `locahost:3000/debug` and switch back and forth while developing(might be only my personal view). No hard feelings if we remove it though 🙂

**Comment by rin-st** [comment]
> I see developers/myself taking inspiration from example-ui.tsx file and directly start editing index.tsx(Homepage)

You can edit `example-ui.tsx` and not even touch `index.tsx` :). So you'll need the homepage only when developing an app

**Comment by carletex** [comment]
Great stuff!!

> I think this is the right time for drafting a PR for yarn surge (surge seems simple, minimal nd comfortable for se-1 devs too ) what do you guys think? Because having a build in functionality to deploy is really great / handy / core before we start sharing with others

Agree, let's go for it! Any of you feel free to assign yourselves to the issue.

> Why? I like the homepage sweat_smile, I see developers/myself taking inspiration from example-ui.tsx file and directly start editing index.tsx(Homepage).
> You can edit example-ui.tsx and not even touch index.tsx :). So you'll need the homepage only when developing an app

Love having different opinions on this! haha. I think we shouldn't do anything for now. At some point in the future, after we (and other devs) use SE2 and we have more feedback, we can re-open the discussion again.
