### ISSUE TITLE
All the reads from contract should work even on wrong network/disconnected

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se-2#134]
if you go to https://test-deploy-iota.vercel.app/debug (contract is deployed on goerli)  you see NO contract found and you need to connect your wallet particularly to goerli to see the contract and even interact with it.

Even though you are on the wrong network / disconnected users should be able to see all the reads from contract

**Comment by carletex** [comment]
On SE1, we have define a `initialNetwork` that is the network that the dApp is supposed to be connected to (same goal as ours `NEXT_PUBLIC_NETWORK`).

And SE1 has these providers/signers:

1. **MainnetProvider**: We always have this, at least for mainnet ENS resolution
2. **LocalProvider**: The selected network for the dApp. If mainnet, it uses the same instance as 1 (since we fixed it :D)
3. **InjectedProvider** (+ signer!): The injected provider (e.g. metamask) that should be on the `initialNetwork` (if not it will show a wrong network warning). Allows you to sign tx.

I think it's a cool approach. We should try to have the same functionality on SE2 with wagmi. On `wagmiConnectors.tsx` we are defining the allowedChains + providers, so it's probably handling all these for us? And it's just a matter on specifying the right `chainId` when using a provider.

As you said, we want all the reads available (for the NEXT_PUBLIC_NETWORK) even if you haven't connected our wallet.

We'll need to figure the best way to structure it, and review our hooks/components that need use (or need to use) the right chainID (for NEXT_PUBLIC_NETWORK).
