### ISSUE TITLE
TS / Lint-staged for begginers

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/se-2#141]
We have a nice lint-staged / precommit workflow (check linting + TS types) + GH Action before merging to `main` that is pretty handy for us.

BUT, we have to keep in mind that this is a starter kit and some of the people that will use SE2 will be beginners, and fighting with TS types is daunting. 

So we need to find a way to disable this for people who choose to do so: Maybe it's just something in the README (instructions on how to remove/disable it). It could also be disabled by default.... and you have to enable (from an .env file?).

Opening the discussion :D

**Comment by carletex** [comment]
Another cool idea:

We could try having a message on top of this (when committing)

![image](https://user-images.githubusercontent.com/2486142/217774666-57151c5c-6ff4-4ee4-8daa-823bb1bb0f90.png)

Like: "If you want to remove this checks, please remove ........."

**Comment by rin-st** [comment]
Since it's TS project, beginners will need to fight with TS anyway, so they can just use `any` for types. If we disable lint-staged, the app can break in some places, and it will be hard to find where and why.

I believe beginners will use mostly our components, and we have to create good docs/comments there to understand how it works. If they'll create their own components, they should know React/TS 🤷‍♂️ . Regarding things like `BigNumber` we also should add info how to work with it. Disabling types more likely will add errors

Also, as I understand GH actions work for PRs to master, but our main branch is `main` so it's disabled. Am I right?

**Comment by technophile-04** [comment]
> Since it's TS project, beginners will need to fight with TS anyway, so they can just use any for types. If we disable lint-staged, the app can break in some places, and it will be hard to find where and why.

💯💯 agree and make complete sense let's not disable it by default instead I think it would helpfull if we mention it somewhere on how to diable it because while hacking in hackathon for 1 day with other teammates sometimes it might get annoying for begginers in typescript hacking with this repo 🙌

I feel the best place will be where Carlos mentioned in his 2nd comment https://github.com/scaffold-eth/se-2/issues/141#issuecomment-1423894870. 

Some command to bypass pre-commit hook : 
1. git commit -m -n "commit message"  - `-n` flag is shorthand for `--no-verify`
2. Comment out `yarn lint-staged --verbose` in `.husky/pre-commit` file

**Comment by carletex** [comment]
We just merged #195

I think we just need to make another PR to update the README with (maybe in a whole new section? We can ask for help to @edakturk14, when we are clear about it):
- Tell people about `yarn vercel:yolo`
- Tell people how to disabled lint-staged (I like option 2 from Shiv )
- Tell people how to disable github actions (delete .github? modify the workflow lint file?)

I 100% agree that good-practices should be the default (specially for us, building the tool), but let's hint people how can the disable all these checks, so newcomers won't get frustrated.

**Comment by edakturk14** [comment]
yes! happy to help out. +1 on the new section as well, since it's more of an extra thing instead of being in the quickstart

**Comment by technophile-04** [comment]
Should we mark this as completed due to #208 ?
