### ISSUE TITLE
Start Foundry Integration

### ISSUE THREAD

**Issue by supernovahs** [scaffold-eth/se-2#201]
I propose to start integrating foundry as the repo is increasing in complexity, it will be prudent to start it now.

We can start by creating a folder named foundry , similar to hardhat.

**Comment by technophile-04** [comment]
Tysm @supernovahs 🙌, love the suggestion but I think we are yet to finalize and start iteration on #121 and #121 seems like the next big thing where Carlos also suggested for Foundry. 

The reason i am referencing #121 is that because adding the foundry to the current state of the repo will make it more confusing/complex/huge on bundle size and yet another thing to handle properly 😅

Currently, there are some core stuff remaining, also need to test it and iterate more, restructure things properly 

Maybe we can start with #121 and Foundry once we are done with the proper MVP and core stuff testing is done? Because there are currently lots of things unhandled which break things 😅

**Comment by supernovahs** [comment]
Sounds good. We should implement it ASAP in the future.
