### ISSUE TITLE
Website theme hardcoded to load light theme until changed

### ISSUE THREAD

**Issue by kevinjoshi46b** [scaffold-eth/se-2#285]
Why is the website theme set to load in light mode instead of users OS mode until changed?

https://github.com/scaffold-eth/se-2/blob/dedd249fed95a858845164424529564b6b51949b/packages/nextjs/components/SwitchTheme.tsx#L6

Why not just remove that `false` and let the website load based on users current OS's mode?

**Comment by sverps** [comment]
Hey @kevinjoshi46b , thanks for the suggestion (and for checking already how to easily change this). I'm not sure if there's a reason why it was set like that, but I agree it would indeed be nice to take the user preference into account (especially since it's trivial to do so).

I created PR #289 for this. (For future reference, if you have other ideas or small fixes, feel free to open a PR alongside the issue)

**Comment by kevinjoshi46b** [comment]
Hey @sverps , happy to help 🫡
I would have opened a PR but before that I just wanted to get to know why was it implemented so, assuming there would have been some reason.
Looking forward to #289 being merged 🚀🚀

**Comment by technophile-04** [comment]
Thanks @kevinjoshi46b for noticing it !!

> I'm not sure if there's a reason why it was set like that, but I agree it would indeed be nice to take the user preference into account 

I don't remember that it had any particular reason, it was added in #83
